apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  ports:
    - name: client
      port: 5432
  selector:
    app: postgresql
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: postgresql
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:9.5
          env:
            - name: POSTGRES_USER
              value: hive
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_DB
              value: metastore
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: hive-metastore
spec:
  ports:
    - name: client
      port: 9083
  selector:
    app: hive-metastore
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: hive-metastore
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hive-metastore
    spec:
      containers:
        - name: hive-metastore
          image: mozdata/docker-hive-metastore:2.1.0
          imagePullPolicy: Always
          env:
            - name: DB_URI
              value: postgresql
            - name: DB_USER
              value: hive
            - name: DB_PASSWORD
              value: password
            - name: CORE_CONF_fs_defaultFS
              value: hdfs://hdfs-namenode:8020
          ports:
            - containerPort: 9083
