apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  ports:
    - name: client
      port: 5432
  selector:
    app: postgresql
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: postgresql
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: bde2020/hive-metastore-postgresql:2.3.0
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: hive-metastore
spec:
  ports:
    - name: client
      port: 9083
  selector:
    app: hive-metastore
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: hive-metastore
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hive-metastore
    spec:
      containers:
        - args:
            - /opt/hive/bin/hive
            - --service
            - metastore
          envFrom:
            - configMapRef:
                name: hive-env
          env:
            - name: SERVICE_PRECONDITION
              value: namenode:50070 datanode:50075 postgresql:5432
          image: bde2020/hive:2.3.2-postgresql-metastore
          name: hive-metastore
          ports:
            - containerPort: 9083
