apiVersion: v1
kind: Service
metadata:
  name: presto
spec:
  type: NodePort
  ports:
    - name: client
      port: 8080
      nodePort: 32766
  selector:
    app: presto
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: presto
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: presto
    spec:
      containers:
        - name: presto
          image: mozdata/docker-presto:0.151
          imagePullPolicy: Always
          env:
            - name: CONFIG_CONF_QUERY_MAX___MEMORY
              value: 128MB
            - name: CONFIG_CONF_QUERY_MAX___MEMORY___PER___NODE
              value: 128MB
            - name: JVM_CONF_XMX
              value: 256M
            - name: HIVE_CONF_HIVE_METASTORE_URI
              value: thrift://hive-metastore:9083
          ports:
            - containerPort: 8080
            - containerPort: 8889
